<a href="https://colab.research.google.com/github/JeongHunShin91/pytorch_training/blob/main/1031__pytorch_training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
torch.__version__

'1.12.1+cu113'

In [4]:
x = torch.empty(4,2)
print(x)

tensor([[1.1669e-35, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]])


In [6]:
x = torch.rand(4,2)
print(x)

tensor([[0.8984, 0.4752],
        [0.7791, 0.9489],
        [0.4068, 0.8287],
        [0.3173, 0.0296]])


In [7]:
x= torch.zeros(4,2,dtype = torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [9]:
x = torch.tensor([3,2.3])
print(x)

tensor([3.0000, 2.3000])


In [13]:
x = x.new_ones(2,4,dtype=torch.double)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [15]:
x = torch.randn_like(x, dtype = torch.float)
print(x)

tensor([[ 0.5847,  0.9394,  0.4055, -0.2857],
        [-1.3001, -0.3556, -0.3917,  0.6924]])


In [16]:
print(x.size())

torch.Size([2, 4])


In [17]:
print(x)

tensor([[ 0.5847,  0.9394,  0.4055, -0.2857],
        [-1.3001, -0.3556, -0.3917,  0.6924]])


In [18]:
y = torch.rand(2,4)
print(x + y)

tensor([[ 1.5455,  1.4510,  0.6244,  0.4356],
        [-1.1638, -0.0073, -0.3181,  0.8026]])


In [19]:
print(torch.add(x,y))

tensor([[ 1.5455,  1.4510,  0.6244,  0.4356],
        [-1.1638, -0.0073, -0.3181,  0.8026]])


In [22]:
result = torch.empty(2,4)
torch.add(x,y,out=result)
print(result)

tensor([[ 1.5455,  1.4510,  0.6244,  0.4356],
        [-1.1638, -0.0073, -0.3181,  0.8026]])


In [23]:
print(x)
print(y)
y.add_(x)
print(y)

tensor([[ 0.5847,  0.9394,  0.4055, -0.2857],
        [-1.3001, -0.3556, -0.3917,  0.6924]])
tensor([[0.9608, 0.5116, 0.2189, 0.7212],
        [0.1362, 0.3483, 0.0736, 0.1101]])
tensor([[ 1.5455,  1.4510,  0.6244,  0.4356],
        [-1.1638, -0.0073, -0.3181,  0.8026]])


In [24]:
x = torch.Tensor([[1,3],
                  [5,7]])
y = torch.Tensor([[2,4],
                  [6,8]])
print(x-y)
print(torch.sub(x,y))
print(x.sub(y))

tensor([[-1., -1.],
        [-1., -1.]])
tensor([[-1., -1.],
        [-1., -1.]])
tensor([[-1., -1.],
        [-1., -1.]])


In [25]:
x = torch.Tensor([[1,3],
                  [5,7]])
y = torch.Tensor([[2,4],
                  [6,8]])
print(x*y)
print(torch.mul(x,y))
print(x.mul(y))

tensor([[ 2., 12.],
        [30., 56.]])
tensor([[ 2., 12.],
        [30., 56.]])
tensor([[ 2., 12.],
        [30., 56.]])


In [26]:
x = torch.Tensor([[1,3],
                  [5,7]])
y = torch.Tensor([[2,4],
                  [6,8]])
print(x/y)
print(torch.div(x,y))
print(x.div(y))

tensor([[0.5000, 0.7500],
        [0.8333, 0.8750]])
tensor([[0.5000, 0.7500],
        [0.8333, 0.8750]])
tensor([[0.5000, 0.7500],
        [0.8333, 0.8750]])


In [27]:
x = torch.Tensor([[1,3],
                  [5,7]])
y = torch.Tensor([[2,4],
                  [6,8]])
print(torch.mm(x,y))

tensor([[20., 28.],
        [52., 76.]])
tensor([[0.5000, 0.7500],
        [0.8333, 0.8750]])
tensor([[0.5000, 0.7500],
        [0.8333, 0.8750]])
